---
  name: PSRule Bicep Validation
  
  on:
    push:
      branches: [ "feature/PSRule-dev" ]
    workflow_dispatch:
  
  jobs:
    Preview-Bicep-Changes:
      runs-on: ubuntu-latest
  
      steps:
        # Checkout code  
      - uses: actions/checkout@v2
  
            # Log into Azure
      - name: Login to Azure  
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      # - name: Run PSRule
      #   uses: pablorechimon/psrule-bicep@latest-exclusions
      #   with:
      #     inputPath: 'deployment/'
      
      - name: Installing Modules
        run: |
          Install-Module -Repository PSGallery -Name PSRule.Rules.Azure -ErrorAction Stop -Scope CurrentUser -Force
          Install-Module -Repository PSGallery -Name Az.Resources -ErrorAction Stop -Scope CurrentUser -Force
        shell: pwsh
        
      - name: Export AZ Rule Data
        run: |
          $json = Export-AzRuleData -Verbose
          Assert-PSRule -InputPath $json.name
        shell: pwsh
  
      - name: Run PSRule analysis for Security
        uses: microsoft/ps-rule@v2.9.0
        with:
          version: '1.11.1'
          modules: 'PSRule.Rules.Azure'
          inputPath: '*.json'