---
name: PSRule Bicep Validation

on:
  push:
    branches: [ "feature/PSRule" ]
  workflow_dispatch:

jobs:
  Preview-Bicep-Changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout code  
    - uses: actions/checkout@v2

    - name: Download PSRule Configuration File
      uses: pablorechimon/psrule-bicep@v1.6
      # run: |
      #   curl -L -O ${{env.psrule_config_url}}
      #   filename=$(basename ${{env.psrule_config_url}})
      #   tar -xvzf $filename --strip-components 1 --exclude="README.md"
      #   ls -la
      
    # - name: Run PSRule analysis
    #   uses: microsoft/ps-rule@v2.9.0
    #   with:
    #     version: '1.11.1'
    #     modules: 'PSRule.Rules.Azure'
    #     inputPath: 'deployment/'
    #     source: '.'  
