---
name: PSRule Bicep Validation

on:
  push:
    branches: [ "feature/PSRule-dev" ]
  workflow_dispatch:

jobs:
  Preview-Bicep-Changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout code  
    - uses: actions/checkout@v2

          # Log into Azure
    - name: Login to Azure  
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PSRule
      uses: pablorechimon/psrule-bicep@latest-exclusions
      with:
        inputPath: 'deployment/'
    
    - name: Export Deployment Data
      run: |
        Install-Module Az.Resources -Force -Scope CurrentUser
        Export-AzRuleData
        Export-AzRuleData
        ls
        Write-Host "Running In flight Validation"
        Assert-PSRule -InputPath '.'
        Write-Host "In flight Validation Completes"
      shell: pwsh
