---
name: PSRule Bicep Validation

on:
  push:
    branches: [ "feature/PSRule-dev" ]
  workflow_dispatch:

jobs:
  Preview-Bicep-Changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout code  
    - uses: actions/checkout@v2

          # Log into Azure
    - name: Login to Azure  
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run PSRule
      uses: pablorechimon/psrule-bicep@v1.1.0
      # run: |
      #   curl -L -O ${{env.psrule_config_url}}
      #   filename=$(basename ${{env.psrule_config_url}})
      #   tar -xvzf $filename --strip-components 1 --exclude="README.md"
      #   ls -la
      
    # - name: Run PSRule analysis
    #   uses: microsoft/ps-rule@v2.9.0
    #   with:
    #     version: '1.11.1'
    #     modules: 'PSRule.Rules.Azure'
    #     inputPath: 'deployment/'
    #     source: '.'  
