---
name: PSRule Bicep Validation

on:
  push:
    branches: [ "feature/PSRule-dev" ]
  workflow_dispatch:

jobs:
  Preview-Bicep-Changes:
    runs-on: windows-latest

    steps:
      # Checkout code  
    - uses: actions/checkout@v2

          # Log into Azure
    - name: Login to Azure  
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Run PSRule
    #   uses: pablorechimon/psrule-bicep@latest-exclusions
    #   with:
    #     inputPath: 'deployment/'
    
    - name: Installing Modules
      run: |
        Install-Module -Repository PSGallery -Name PSRule.Rules.Azure -ErrorAction Stop -Scope CurrentUser -Force
        Install-Module -Repository PSGallery -Name Az.Resources -ErrorAction Stop -Scope CurrentUser -Force
        Install-Module -Repository PSGallery -Name Az.Accounts -ErrorAction Stop -Scope CurrentUser -Force
        Uninstall-AzureRm
      shell: pwsh
      
    - name: Testing
      run: |
        dir
        Set-AzContext -Tenant '45e46c0f-a5d5-40dd-b10b-d8311cca261e' -Subscription 'ea93148e-4b2f-4f06-b7fb-2c8ecc309d3f'
        Get-AzContext
        $TestResult = Export-AzRuleData -Verbose
        $TestResult
        Get-Error
        dir
        Write-Host "Running In flight Validation"
        Assert-PSRule -InputPath '.'
        Write-Host "In flight Validation Completes"
      shell: pwsh
