on: [push]
name: Azure ARM
jobs:
  Deploy-Bicep-from-ACR:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Bicep Deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: |
          /deployment/storage-resource.bicep
          /deployment/appservice-resource.bicep
          #./deployment/storage-resource.bicep
        #parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false